# Synthetic Healthcare Data Factory

## Project Overview

This project uses LLM to generate synthetic healthcare data.

Synthetic data is artificial data that looks similar to real-world data does not belong to real patients.

We will use different AI models and propmts to generate structured healthcare datasets that can be used for data science, analytics and AI projects.

For this project, we will start with synthetic Prior Authorization data.

## Business Problem

Healthcare data is useful for building and testing data science and AI applications.

However, real patient data contains sensitive information and cannot always be easily accessed or shared.

Synthetic data provides a way to create realistic examples without using real patient information.

Instead of manually creating hundreds of records, we can use LLMs to generate structured synthetic datasets automatically.

## Project Objective

The goal of this project is to build a simple synthetic data generator that can:

- Describe the type of data we want to generate
- Define the structure of the dataset
- Generate synthetic records using an LLM
- Use different prompts to create diverse data
- Compare data generated by different AI models
- Check the quality of the generated data
- Save the final dataset for future projects

All patient information generated in this project will be fictional.

## Our First Dataset

We will start with a Prior Authorization dataset.

Prior authorization is a process where a healthcare provider may need approval from an insurance company before certain healthcare services are provided.

Each synthetic record will represent a fictional prior authorization request.

Later, the same approach can be used to generate other types of healthcare data.

In [2]:
dataset_name = "Prior Authorization"

fields = [
    "patient_id",
    "age",
    "gender",
    "insurance_provider",
    "service",
    "diagnosis_category",
    "physician_order",
    "clinical_notes",
    "previous_imaging",
    "authorization_status"
]

print("Dataset:", dataset_name)
print("\nFields:")

for field in fields:
    print("-", field)

Dataset: Prior Authorization

Fields:
- patient_id
- age
- gender
- insurance_provider
- service
- diagnosis_category
- physician_order
- clinical_notes
- previous_imaging
- authorization_status

We created a simple definition for our first synthetic dataset.

The dataset represents fictional prior authorization requests.

The fields describe information such as the patient's age, insurance provider, requested service, available documents and authorization status.

Defining the fields first helps us clearly tell the LLM what type of structured data we want it to generate.

## Step 2: Imports and Model Setup

In [3]:
# Step 1: Importing Libraries
import os
import json
import pandas as pd
from dotenv import load_dotenv
from openai import OpenAI

In [4]:
# Checking API Key is loaded or not
load_dotenv(override=True)

openai_api_key = os.getenv("OPENAI_API_KEY")

if openai_api_key:
    print("OpenAI API Key loaded successfully")
else:
    print("OpenAI API Key not found")

OpenAI API Key loaded successfully

In [5]:
# OpenAI Client and selecting the first model that will use to generate synthetic data
openai = OpenAI()
MODEL = "gpt-4.1-mini"

print("Model:", MODEL)

Model: gpt-4.1-mini

## Step 3: Generate Our First Synthetic Healthcare Records.

## Generate Our First Synthetic Data

Now we will use an LLM to generate our first synthetic Prior Authorization records.

We will start with only 5 records so we can easily review the output.

We will tell the model:
- What type of data we need
- Which fields to include
- That the patients must be fictional
- That the output should be structured as JSON

Later, we will improve the prompt and generate larger datasets.

In [6]:
prompt = """
Generate 5 fictional healthcare Prior Authorization records.

Use these fields:

- patient_id
- age
- gender
- insurance_provider
- service
- diagnosis_category
- physician_order
- clinical_notes
- previous_imaging
- authorization_status

Requirements:

- Do not use real patient information.
- Use different patients, services and insurance providers.
- Use realistic but fictional healthcare examples.
- physician_order, clinical_notes and previous_imaging should be true or false.
- authorization_status should be Approved, Pending or Denied.
- Return only a JSON array.
"""

In [7]:
# Lets send the prompt to our first model
response = openai.chat.completions.create(
    model=MODEL,
    messages=[{"role": "user","content": prompt}]
)

generated_data = response.choices[0].message.content

print(generated_data)

```json
[
  {
    "patient_id": "P1001",
    "age": 45,
    "gender": "Female",
    "insurance_provider": "HealthFirst",
    "service": "MRI Brain",
    "diagnosis_category": "Neurology",
    "physician_order": true,
    "clinical_notes": true,
    "previous_imaging": false,
    "authorization_status": "Approved"
  },
  {
    "patient_id": "P1002",
    "age": 62,
    "gender": "Male",
    "insurance_provider": "WellCare",
    "service": "CT Abdomen",
    "diagnosis_category": "Gastroenterology",
    "physician_order": true,
    "clinical_notes": false,
    "previous_imaging": true,
    "authorization_status": "Pending"
  },
  {
    "patient_id": "P1003",
    "age": 29,
    "gender": "Female",
    "insurance_provider": "UnitedHealth",
    "service": "Physical Therapy",
    "diagnosis_category": "Orthopedics",
    "physician_order": true,
    "clinical_notes": true,
    "previous_imaging": false,
    "authorization_status": "Approved"
  },
  {
    "patient_id": "P1004",
    "age": 54,
    "gender": "Male",
    "insurance_provider": "Aetna",
    "service": "Cardiac Stress Test",
    "diagnosis_category": "Cardiology",
    "physician_order": false,
    "clinical_notes": true,
    "previous_imaging": true,
    "authorization_status": "Denied"
  },
  {
    "patient_id": "P1005",
    "age": 38,
    "gender": "Female",
    "insurance_provider": "Cigna",
    "service": "Ultrasound Pelvis",
    "diagnosis_category": "Gynecology",
    "physician_order": true,
    "clinical_notes": false,
    "previous_imaging": false,
    "authorization_status": "Pending"
  }
]
```

## Step 4: Convert the LLM Output into Structured Data.

## Convert the Generated Data

The LLM returned our synthetic records as text.

Before we can analyze the data, we need to convert the text into structured Python data.

Sometimes an LLM adds Markdown formatting such as ```json around the response.

We will first remove this formatting and then convert the JSON text into Python.

In [8]:
cleaned_data = generated_data.strip()

cleaned_data = cleaned_data.replace("```json", "")
cleaned_data = cleaned_data.replace("```", "")
cleaned_data = cleaned_data.strip()

print(cleaned_data)

[
  {
    "patient_id": "P1001",
    "age": 45,
    "gender": "Female",
    "insurance_provider": "HealthFirst",
    "service": "MRI Brain",
    "diagnosis_category": "Neurology",
    "physician_order": true,
    "clinical_notes": true,
    "previous_imaging": false,
    "authorization_status": "Approved"
  },
  {
    "patient_id": "P1002",
    "age": 62,
    "gender": "Male",
    "insurance_provider": "WellCare",
    "service": "CT Abdomen",
    "diagnosis_category": "Gastroenterology",
    "physician_order": true,
    "clinical_notes": false,
    "previous_imaging": true,
    "authorization_status": "Pending"
  },
  {
    "patient_id": "P1003",
    "age": 29,
    "gender": "Female",
    "insurance_provider": "UnitedHealth",
    "service": "Physical Therapy",
    "diagnosis_category": "Orthopedics",
    "physician_order": true,
    "clinical_notes": true,
    "previous_imaging": false,
    "authorization_status": "Approved"
  },
  {
    "patient_id": "P1004",
    "age": 54,
    "gender": "Male",
    "insurance_provider": "Aetna",
    "service": "Cardiac Stress Test",
    "diagnosis_category": "Cardiology",
    "physician_order": false,
    "clinical_notes": true,
    "previous_imaging": true,
    "authorization_status": "Denied"
  },
  {
    "patient_id": "P1005",
    "age": 38,
    "gender": "Female",
    "insurance_provider": "Cigna",
    "service": "Ultrasound Pelvis",
    "diagnosis_category": "Gynecology",
    "physician_order": true,
    "clinical_notes": false,
    "previous_imaging": false,
    "authorization_status": "Pending"
  }
]

We removed the extra Markdown formatting from the LLM response.

In [9]:
# The data is still JSON text, but it is now ready to be converted into Python.
records = json.loads(cleaned_data)

print("Number of records:", len(records))
print("Data type:", type(records))

Number of records: 5
Data type: <class 'list'>

In [10]:
# Convert into Dataframe
df = pd.DataFrame(records)
df

,patient_id,age,gender,insurance_provider,service,diagnosis_category,physician_order,clinical_notes,previous_imaging,authorization_status
0,P1001,45,Female,HealthFirst,MRI Brain,Neurology,True,True,False,Approved
1,P1002,62,Male,WellCare,CT Abdomen,Gastroenterology,True,False,True,Pending
2,P1003,29,Female,UnitedHealth,Physical Therapy,Orthopedics,True,True,False,Approved
3,P1004,54,Male,Aetna,Cardiac Stress Test,Cardiology,False,True,True,Denied
4,P1005,38,Female,Cigna,Ultrasound Pelvis,Gynecology,True,False,False,Pending

We converted the synthetic records into a Pandas DataFrame.

This gives us a structured table where each row represents one fictional Prior Authorization request and each column represents a field.

The data is now much easier to view, analyze and validate.

## Step 5: Improving the Prompt for More Diverse Synthetic Data

## Improving Data Diversity

Our first prompt successfully generated structured synthetic data.

However, when generating larger datasets, we do not want every record to look similar.

We can improve the prompt by asking the model to create more variety in areas such as:

- Patient age
- Gender
- Insurance provider
- Healthcare service
- Diagnosis category
- Available documents
- Authorization status

This helps us create a more diverse dataset for testing and data science projects.

In [11]:
diversity_prompt = """
Generate 5 diverse and fictional healthcare Prior Authorization records.

Use these fields:

- patient_id
- age
- gender
- insurance_provider
- service
- diagnosis_category
- physician_order
- clinical_notes
- previous_imaging
- authorization_status

Requirements:

- Do not use real patient information.
- Include patients from different age groups.
- Use different genders.
- Use different fictional insurance providers.
- Include different healthcare services.
- Include different diagnosis categories.
- Create different combinations of available and missing documents.
- Include a mix of Approved, Pending and Denied authorization statuses.
- Avoid repeating the same type of record.
- Return only a JSON array.
"""

This prompt gives the LLM more instructions about diversity.

Instead of simply asking for different records, we describe the types of variation we want in the dataset.

This gives us more control over the synthetic data being generated.

In [12]:
response = openai.chat.completions.create(
    model=MODEL,
    messages=[{"role": "user","content": diversity_prompt}]
)

diverse_data = response.choices[0].message.content

print(diverse_data)

```json
[
  {
    "patient_id": "P1001A",
    "age": 72,
    "gender": "Female",
    "insurance_provider": "HealthSecure Plus",
    "service": "MRI Brain with Contrast",
    "diagnosis_category": "Neurology",
    "physician_order": "Order#NS-4873",
    "clinical_notes": "Patient exhibits progressive memory loss and occasional dizziness. Rule out cerebrovascular events.",
    "previous_imaging": "CT Head without contrast from 3 months ago available.",
    "authorization_status": "Approved"
  },
  {
    "patient_id": "P2045B",
    "age": 28,
    "gender": "Male",
    "insurance_provider": "CareFirst Alliance",
    "service": "Physical Therapy - 12 sessions",
    "diagnosis_category": "Orthopedics",
    "physician_order": "Order#OR-9921",
    "clinical_notes": "Post ACL reconstruction surgery. Recommend therapy to improve joint mobility and strength.",
    "previous_imaging": null,
    "authorization_status": "Pending"
  },
  {
    "patient_id": "P3333C",
    "age": 45,
    "gender": "Non-binary",
    "insurance_provider": "MediPrime Coverage",
    "service": "CT Abdomen and Pelvis with Contrast",
    "diagnosis_category": "Gastroenterology",
    "physician_order": "Order#GI-5532",
    "clinical_notes": "Chronic abdominal pain with unexplained weight loss. Evaluate for possible masses or inflammation.",
    "previous_imaging": "Ultrasound abdomen done 6 weeks ago available.",
    "authorization_status": "Denied"
  },
  {
    "patient_id": "P9872D",
    "age": 5,
    "gender": "Male",
    "insurance_provider": "FamilyHealth Network",
    "service": "Audiology Evaluation",
    "diagnosis_category": "Pediatrics",
    "physician_order": "Order#PD-2209",
    "clinical_notes": "Child has delayed speech development and suspected hearing loss.",
    "previous_imaging": null,
    "authorization_status": "Approved"
  },
  {
    "patient_id": "P4490E",
    "age": 58,
    "gender": "Female",
    "insurance_provider": "SecureWell Insurance",
    "service": "Colonoscopy Screening",
    "diagnosis_category": "Preventive Care",
    "physician_order": "Order#PC-8001",
    "clinical_notes": "Routine colorectal cancer screening; family history positive for colon cancer.",
    "previous_imaging": null,
    "authorization_status": "Pending"
  }
]
```

We generated a second set of synthetic records using the diversity-focused prompt.

We used the same AI model as before.

This allows us to see how changing only the prompt can influence the type and variety of data generated by the model.

In [13]:
# Clean the JSON strips, like we did earlier
cleaned_diverse_data = diverse_data.strip()

cleaned_diverse_data = cleaned_diverse_data.replace("```json", "")
cleaned_diverse_data = cleaned_diverse_data.replace("```", "")
cleaned_diverse_data = cleaned_diverse_data.strip()

diverse_records = json.loads(cleaned_diverse_data)

In [14]:
diverse_df = pd.DataFrame(diverse_records)
diverse_df

,patient_id,age,gender,insurance_provider,service,diagnosis_category,physician_order,clinical_notes,previous_imaging,authorization_status
0,P1001A,72,Female,HealthSecure Plus,MRI Brain with Contrast,Neurology,Order#NS-4873,Patient exhibits progressive memory loss and o...,CT Head without contrast from 3 months ago ava...,Approved
1,P2045B,28,Male,CareFirst Alliance,Physical Therapy - 12 sessions,Orthopedics,Order#OR-9921,Post ACL reconstruction surgery. Recommend the...,None,Pending
2,P3333C,45,Non-binary,MediPrime Coverage,CT Abdomen and Pelvis with Contrast,Gastroenterology,Order#GI-5532,Chronic abdominal pain with unexplained weight...,Ultrasound abdomen done 6 weeks ago available.,Denied
3,P9872D,5,Male,FamilyHealth Network,Audiology Evaluation,Pediatrics,Order#PD-2209,Child has delayed speech development and suspe...,None,Approved
4,P4490E,58,Female,SecureWell Insurance,Colonoscopy Screening,Preventive Care,Order#PC-8001,Routine colorectal cancer screening; family hi...,None,Pending

In [15]:
# compare it with our original dataset to see whether the diversity-focused prompt created more variation.
print("Original Dataset")
print("Unique services:", df["service"].nunique())
print("Unique diagnosis categories:", df["diagnosis_category"].nunique())
print("Authorization statuses:", df["authorization_status"].unique())

print("\nDiversity Prompt Dataset")
print("Unique services:", diverse_df["service"].nunique())
print("Unique diagnosis categories:", diverse_df["diagnosis_category"].nunique())
print("Authorization statuses:", diverse_df["authorization_status"].unique())

Original Dataset
Unique services: 5
Unique diagnosis categories: 5
Authorization statuses: ['Approved' 'Pending' 'Denied']

Diversity Prompt Dataset
Unique services: 5
Unique diagnosis categories: 5
Authorization statuses: ['Approved' 'Pending' 'Denied']

### Observation

Both prompts generated 5 unique services, 5 unique diagnosis categories and all three authorization statuses.

In this small example, the original prompt already produced diverse records, so the diversity-focused prompt did not show an improvement in these measures.

Later, we will generate more records and use different prompts and models to make a better comparison.

## Step 6: Generate Edge Cases

Real-world datasets do not contain only simple and complete records.

They can also contain cases with missing documents, denied requests, incomplete information or unusual combinations.

We will use a different prompt to intentionally generate these types of edge cases.

This can help create better datasets for testing AI and data science applications.

In [16]:
# Third Prompt
edge_case_prompt = """
Generate 5 fictional healthcare Prior Authorization edge-case records.

Use these fields:

- patient_id
- age
- gender
- insurance_provider
- service
- diagnosis_category
- physician_order
- clinical_notes
- previous_imaging
- authorization_status

Create examples that include situations such as:

- Missing physician orders
- Missing clinical notes
- Missing previous imaging
- Denied authorization requests
- Pending authorization requests
- Different healthcare services and diagnosis categories

Requirements:

- Do not use real patient information.
- Make each record different.
- physician_order, clinical_notes and previous_imaging should be true or false.
- authorization_status should be Approved, Pending or Denied.
- Return only a JSON array.
"""

This prompt focuses specifically on edge cases. Instead of asking the model for general records, we are asking it to create examples with missing documents and different authorization outcomes.

These records can be useful when testing whether another system can correctly handle unusual or incomplete cases.

In [17]:
response = openai.chat.completions.create(
    model=MODEL,
    messages=[{"role": "user","content": edge_case_prompt}]
)

edge_case_data = response.choices[0].message.content

print(edge_case_data)

```json
[
  {
    "patient_id": "P1001",
    "age": 45,
    "gender": "Female",
    "insurance_provider": "HealthFirst",
    "service": "MRI Brain",
    "diagnosis_category": "Neurology",
    "physician_order": false,
    "clinical_notes": true,
    "previous_imaging": true,
    "authorization_status": "Denied"
  },
  {
    "patient_id": "P1002",
    "age": 60,
    "gender": "Male",
    "insurance_provider": "MediCare Plus",
    "service": "Cardiac Stress Test",
    "diagnosis_category": "Cardiology",
    "physician_order": true,
    "clinical_notes": false,
    "previous_imaging": true,
    "authorization_status": "Pending"
  },
  {
    "patient_id": "P1003",
    "age": 30,
    "gender": "Female",
    "insurance_provider": "WellCare",
    "service": "Ultrasound Abdomen",
    "diagnosis_category": "Gastroenterology",
    "physician_order": true,
    "clinical_notes": true,
    "previous_imaging": false,
    "authorization_status": "Approved"
  },
  {
    "patient_id": "P1004",
    "age": 55,
    "gender": "Male",
    "insurance_provider": "SecureHealth",
    "service": "Physical Therapy",
    "diagnosis_category": "Orthopedics",
    "physician_order": true,
    "clinical_notes": true,
    "previous_imaging": true,
    "authorization_status": "Pending"
  },
  {
    "patient_id": "P1005",
    "age": 70,
    "gender": "Female",
    "insurance_provider": "PrimeCare",
    "service": "Chest X-Ray",
    "diagnosis_category": "Pulmonology",
    "physician_order": true,
    "clinical_notes": false,
    "previous_imaging": false,
    "authorization_status": "Denied"
  }
]
```

The model generated a new set of synthetic records using our edge-case prompt.

In [18]:
# Convert Records into Pandas Dataframe for easy to review.
cleaned_edge_data = edge_case_data.strip()

cleaned_edge_data = cleaned_edge_data.replace("```json", "")
cleaned_edge_data = cleaned_edge_data.replace("```", "")
cleaned_edge_data = cleaned_edge_data.strip()

edge_records = json.loads(cleaned_edge_data)

edge_df = pd.DataFrame(edge_records)

edge_df

,patient_id,age,gender,insurance_provider,service,diagnosis_category,physician_order,clinical_notes,previous_imaging,authorization_status
0,P1001,45,Female,HealthFirst,MRI Brain,Neurology,False,True,True,Denied
1,P1002,60,Male,MediCare Plus,Cardiac Stress Test,Cardiology,True,False,True,Pending
2,P1003,30,Female,WellCare,Ultrasound Abdomen,Gastroenterology,True,True,False,Approved
3,P1004,55,Male,SecureHealth,Physical Therapy,Orthopedics,True,True,True,Pending
4,P1005,70,Female,PrimeCare,Chest X-Ray,Pulmonology,True,False,False,Denied

In [19]:
# let's measure what the edge-case prompt produced
print("Total records:", len(edge_df))

print("\nMissing Physician Order:")
print((edge_df["physician_order"] == False).sum())

print("\nMissing Clinical Notes:")
print((edge_df["clinical_notes"] == False).sum())

print("\nMissing Previous Imaging:")
print((edge_df["previous_imaging"] == False).sum())

print("\nAuthorization Status:")
print(edge_df["authorization_status"].value_counts())

Total records: 5

Missing Physician Order:
1

Missing Clinical Notes:
2

Missing Previous Imaging:
2

Authorization Status:
authorization_status
Denied      2
Pending     2
Approved    1
Name: count, dtype: int64

### Observation

The edge-case prompt intentionally creates records with missing information and different authorization outcomes.

This shows how different prompts can be used to generate specific types of synthetic data.

Instead of relying on one prompt to generate every type of record, we can use different prompts to create normal, diverse and edge-case examples.

Standard Prompt
      ↓
General synthetic records

Diversity Prompt
      ↓
Different services, diagnoses and patient characteristics

Edge-Case Prompt
      ↓
Missing information and difficult cases

## Generate Data using Different Models

We have generated sunthetic data using OpenAI model.

we will now use second model to generate same type of sunthetic healthcare data.

Later, we will compare the outputs from different models.

In [20]:
# Using Ollama
ollama = OpenAI(
    base_url="http://localhost:11434/v1",
    api_key="ollama"
)

OLLAMA_MODEL = "llama3.2"

print("Second model:", OLLAMA_MODEL)

Second model: llama3.2

In [21]:
# Ollama generated synthetic data
llama_response = ollama.chat.completions.create(
    model=OLLAMA_MODEL,
    messages=[{"role": "user","content": prompt}]
)

llama_data = llama_response.choices[0].message.content

print(llama_data)

Here are five fictional healthcare Prior Authorization records in JSON format:

[
    {
        "patient_id": "P001",
        "age": "35",
        "gender": "Female",
        "insurance_provider": "Astra Health",
        "service": "Surgery",
        "diagnosis_category": "Cancer",
        "physician_order": true,
        "clinical_notes": true,
        "previous_imaging": true,
        "authorization_status": "Approved"
    },
    {
        "patient_id": "P002",
        "age": "42",
        "gender": "Male",
        "insurance_provider": "MedSure Insurance",
        "service": "MRI Scan",
        "diagnosis_category": "Musculoskeletal",
        "physician_order": false,
        "clinical_notes": true,
        "previous_imaging": false,
        "authorization_status": "Pending"
    },
    {
        "patient_id": "P003",
        "age": "28",
        "gender": "Female",
        "insurance_provider": "Aria Health",
        "service": "Physical Therapy",
        "diagnosis_category": "Neurological",
        "physician_order": true,
        "clinical_notes": false,
        "previous_imaging": true,
        "authorization_status": "Denied"
    },
    {
        "patient_id": "P004",
        "age": "45",
        "gender": "Male",
        "insurance_provider": "StarMed Insurance",
        "service": "Cancer Treatment",
        "diagnosis_category": "Hematological",
        "physician_order": true,
        "clinical_notes": true,
        "previous_imaging": true,
        "authorization_status": "Approved"
    },
    {
        "patient_id": "P005",
        "age": "32",
        "gender": "Female",
        "insurance_provider": "CareWell Insurance",
        "service": "Pulmonary Test",
        "diagnosis_category": "Respiratory",
        "physician_order": false,
        "clinical_notes": true,
        "previous_imaging": false,
        "authorization_status": "Pending"
    }
]

In [22]:
# Convert it to structured Python data
cleaned_llama_data = llama_data.strip()

# Find where the JSON array starts and ends
start = cleaned_llama_data.find("[")
end = cleaned_llama_data.rfind("]")

# Keep only the JSON array
cleaned_llama_data = cleaned_llama_data[start:end + 1]

# Convert JSON into Python
llama_records = json.loads(cleaned_llama_data)

In [23]:
# Convert Python data into a DataFrame
llama_df = pd.DataFrame(llama_records)

llama_df

,patient_id,age,gender,insurance_provider,service,diagnosis_category,physician_order,clinical_notes,previous_imaging,authorization_status
0,P001,35,Female,Astra Health,Surgery,Cancer,True,True,True,Approved
1,P002,42,Male,MedSure Insurance,MRI Scan,Musculoskeletal,False,True,False,Pending
2,P003,28,Female,Aria Health,Physical Therapy,Neurological,True,False,True,Denied
3,P004,45,Male,StarMed Insurance,Cancer Treatment,Hematological,True,True,True,Approved
4,P005,32,Female,CareWell Insurance,Pulmonary Test,Respiratory,False,True,False,Pending

In [24]:
print("OpenAI Model:", MODEL)
print("Records:", len(df))
print("Unique services:", df["service"].nunique())
print("Unique diagnosis categories:", df["diagnosis_category"].nunique())
print("Authorization statuses:", df["authorization_status"].unique())

print("\nLlama Model:", OLLAMA_MODEL)
print("Records:", len(llama_df))
print("Unique services:", llama_df["service"].nunique())
print("Unique diagnosis categories:", llama_df["diagnosis_category"].nunique())
print("Authorization statuses:", llama_df["authorization_status"].unique())

OpenAI Model: gpt-4.1-mini
Records: 5
Unique services: 5
Unique diagnosis categories: 5
Authorization statuses: ['Approved' 'Pending' 'Denied']

Llama Model: llama3.2
Records: 5
Unique services: 5
Unique diagnosis categories: 5
Authorization statuses: ['Approved' 'Pending' 'Denied']

## Create a Resuable Function

## Create a Reusable Data Generator

So far, we have repeated similar code each time we generate synthetic data.

We will now create a simple function that can:

1. Receive a prompt
2. Send the prompt to an AI model
3. Get the generated response
4. Extract the JSON data
5. Convert it into a Pandas DataFrame

This will make it easier to generate more datasets using different models and prompts.

In [25]:
def generate_synthetic_data(client, model, prompt):

    response = client.chat.completions.create(
        model=model,
        messages=[{"role": "user","content": prompt}])

    generated_text = response.choices[0].message.content

    start = generated_text.find("[")
    end = generated_text.rfind("]")

    json_text = generated_text[start:end + 1]

    records = json.loads(json_text)
    return pd.DataFrame(records)

The function combines the main steps of our synthetic data generation process.

We provide:

- The AI client
- The model
- The prompt

The function sends the request to the model, finds the JSON array in the response and converts the generated records into a Pandas DataFrame.

This allows us to reuse the same process with different models and prompts.

In [26]:
# Testing GPT Model
gpt_df = generate_synthetic_data(openai,MODEL,prompt)
gpt_df

,patient_id,age,gender,insurance_provider,service,diagnosis_category,physician_order,clinical_notes,previous_imaging,authorization_status
0,P00123,45,Female,HealthFirst,MRI Brain with Contrast,Neurology,True,True,False,Approved
1,P00456,62,Male,MediCare Plus,Physical Therapy - Shoulder,Orthopedics,True,True,True,Pending
2,P00789,29,Female,WellCare,CT Abdomen and Pelvis,Gastroenterology,False,True,False,Denied
3,P01011,53,Male,United Health,Cardiac Stress Test,Cardiology,True,False,True,Approved
4,P01234,38,Female,Aetna,Ultrasound Pelvis,Gynecology,True,True,False,Pending

In [27]:
# Testing LLAMA Model
llama_df = generate_synthetic_data(ollama,OLLAMA_MODEL,prompt)
llama_df

,patient_id,age,gender,insurance_provider,service,diagnosis_category,physician_order,clinical_notes,previous_imaging,authorization_status
0,123456,32,Female,AxxoHealth,Pain Management,Musculoskeletal,True,True,False,Approved
1,789012,55,Male,BriteHealth,Cardiovascular Surgery,Cardiology,False,True,True,Pending
2,901234,28,Male,AxxoHealth,Neurosurgery,Neurology,True,True,False,Denied
3,111122,42,Female,BriteHealth,Physical Therapy,Orthopedics,False,True,True,Approved
4,222233,65,Female,AxxoHealth,Hospice Care,Terminal Illness,True,True,False,Pending

## Third Model: Gemini

In [33]:
gemini_api_key = os.getenv("GOOGLE_API_KEY")

if gemini_api_key:
    print("Gemini API Key loaded successfully")
else:
    print("Gemini API Key not found")

Gemini API Key loaded successfully

In [35]:
from google import genai

gemini = genai.Client(api_key=gemini_api_key)

GEMINI_MODEL = "gemini-3.8-flash"

print("Third model:", GEMINI_MODEL)

Third model: gemini-3.8-flash

In [41]:
gemini_response = gemini.models.generate_content(
    model=GEMINI_MODEL,
    contents=prompt
)

gemini_data = gemini_response.text
print(gemini_data)

Warning: there are non-text parts in the response: ['thought_signature'], returning concatenated text result from text parts. Check the full candidates.content.parts accessor to get the full model response.

[
  {
    "patient_id": "PT-90412",
    "age": 58,
    "gender": "Male",
    "insurance_provider": "Blue Cross Blue Shield",
    "service": "MRI Lumbar Spine without Contrast",
    "diagnosis_category": "Musculoskeletal",
    "physician_order": true,
    "clinical_notes": true,
    "previous_imaging": true,
    "authorization_status": "Approved"
  },
  {
    "patient_id": "PT-31845",
    "age": 42,
    "gender": "Female",
    "insurance_provider": "Aetna",
    "service": "Infliximab IV Infusion Therapy",
    "diagnosis_category": "Gastroenterology",
    "physician_order": true,
    "clinical_notes": true,
    "previous_imaging": false,
    "authorization_status": "Pending"
  },
  {
    "patient_id": "PT-77209",
    "age": 67,
    "gender": "Male",
    "insurance_provider": "UnitedHealthcare",
    "service": "Total Knee Arthroplasty (Left)",
    "diagnosis_category": "Orthopedics",
    "physician_order": true,
    "clinical_notes": false,
    "previous_imaging": true,
    "authorization_status": "Denied"
  },
  {
    "patient_id": "PT-14983",
    "age": 34,
    "gender": "Female",
    "insurance_provider": "Cigna",
    "service": "Diagnostic Polysomnography (Sleep Study)",
    "diagnosis_category": "Pulmonology",
    "physician_order": true,
    "clinical_notes": true,
    "previous_imaging": false,
    "authorization_status": "Approved"
  },
  {
    "patient_id": "PT-65230",
    "age": 73,
    "gender": "Female",
    "insurance_provider": "Humana",
    "service": "PET Scan Whole Body",
    "diagnosis_category": "Oncology",
    "physician_order": false,
    "clinical_notes": true,
    "previous_imaging": true,
    "authorization_status": "Denied"
  }
]

In [42]:
cleaned_gemini_data = gemini_data.strip()

start = cleaned_gemini_data.find("[")
end = cleaned_gemini_data.rfind("]")

cleaned_gemini_data = cleaned_gemini_data[start:end + 1]

gemini_records = json.loads(cleaned_gemini_data)

In [43]:
# Converting into Dataframe
gemini_df = pd.DataFrame(gemini_records)
gemini_df

,patient_id,age,gender,insurance_provider,service,diagnosis_category,physician_order,clinical_notes,previous_imaging,authorization_status
0,PT-90412,58,Male,Blue Cross Blue Shield,MRI Lumbar Spine without Contrast,Musculoskeletal,True,True,True,Approved
1,PT-31845,42,Female,Aetna,Infliximab IV Infusion Therapy,Gastroenterology,True,True,False,Pending
2,PT-77209,67,Male,UnitedHealthcare,Total Knee Arthroplasty (Left),Orthopedics,True,False,True,Denied
3,PT-14983,34,Female,Cigna,Diagnostic Polysomnography (Sleep Study),Pulmonology,True,True,False,Approved
4,PT-65230,73,Female,Humana,PET Scan Whole Body,Oncology,False,True,True,Denied

The Gemini response has now been converted into a Pandas DataFrame.

We now have synthetic Prior Authorization datasets generated by three different model families:

- GPT-4.1-mini
- Llama 3.2
- Gemini

In [44]:
# Compare All Three Models
print("OpenAI Model:", MODEL)
print("Records:", len(df))
print("Unique services:", df["service"].nunique())
print("Unique diagnosis categories:", df["diagnosis_category"].nunique())
print("Authorization statuses:", df["authorization_status"].unique())

print("\nLlama Model:", OLLAMA_MODEL)
print("Records:", len(llama_df))
print("Unique services:", llama_df["service"].nunique())
print("Unique diagnosis categories:", llama_df["diagnosis_category"].nunique())
print("Authorization statuses:", llama_df["authorization_status"].unique())

print("\nGemini Model:", GEMINI_MODEL)
print("Records:", len(gemini_df))
print("Unique services:", gemini_df["service"].nunique())
print("Unique diagnosis categories:", gemini_df["diagnosis_category"].nunique())
print("Authorization statuses:", gemini_df["authorization_status"].unique())

OpenAI Model: gpt-4.1-mini
Records: 5
Unique services: 5
Unique diagnosis categories: 5
Authorization statuses: ['Approved' 'Pending' 'Denied']

Llama Model: llama3.2
Records: 5
Unique services: 5
Unique diagnosis categories: 5
Authorization statuses: ['Approved' 'Pending' 'Denied']

Gemini Model: gemini-3.8-flash
Records: 5
Unique services: 5
Unique diagnosis categories: 5
Authorization statuses: ['Approved' 'Pending' 'Denied']

### Initial Multi-Model Comparison

We generated the same type of synthetic healthcare data using three different AI model families.

This allows us to compare how different models respond to the same data generation instructions.

For each model, we are currently comparing:

- Number of generated records
- Number of unique healthcare services
- Number of unique diagnosis categories
- Authorization status variety

Because each model generated only 5 records, this is still a small experiment.

We will generate a larger dataset later to perform a more meaningful comparison.

                    Same Healthcare Prompt
                             |
          ┌──────────────────┼──────────────────┐
          ↓                  ↓                  ↓
    GPT-4.1-mini         Llama 3.2          Gemini
      OpenAI               Local             Google
          ↓                  ↓                  ↓
      JSON/Text           JSON/Text          JSON/Text
          └──────────────────┼──────────────────┘
                             ↓
                      Clean the Output
                             ↓
                      Pandas DataFrames
                             ↓
                       Compare Results

## Generate a Larger Synthetic Dataset

So far, we have generated small groups of 5 records to test our prompts and models.

We will now generate multiple batches of synthetic Prior Authorization records using different prompt strategies.

We will start by using GPT-4.1-mini because it generated structured data successfully and quickly.

Later, we can combine records generated by different models.

In [45]:
standard_batch = generate_synthetic_data(openai,MODEL,prompt)

diversity_batch = generate_synthetic_data(openai,MODEL,diversity_prompt)

edge_batch = generate_synthetic_data(openai,MODEL,edge_case_prompt)

print("Standard records:", len(standard_batch))
print("Diversity records:", len(diversity_batch))
print("Edge-case records:", len(edge_batch))

Standard records: 5
Diversity records: 5
Edge-case records: 5

We generated three different batches of synthetic data.

Each batch was created for a different purpose:

- **Standard** creates general Prior Authorization records.
- **Diversity** encourages variety across patients, services and diagnoses.
- **Edge Case** intentionally creates more difficult or incomplete examples.

Next, we will label each batch so that we know which prompt generated each record.

In [46]:
standard_batch["prompt_type"] = "Standard"
diversity_batch["prompt_type"] = "Diversity"
edge_batch["prompt_type"] = "Edge Case"

standard_batch["model"] = MODEL
diversity_batch["model"] = MODEL
edge_batch["model"] = MODEL

We added two metadata columns:

- `prompt_type` tells us which prompt strategy generated the record.
- `model` tells us which AI model generated the record.

Keeping this information allows us to analyze and compare the synthetic data later.

In [47]:
larger_df = pd.concat([standard_batch,diversity_batch,edge_batch], ignore_index=True)
larger_df

,patient_id,age,gender,insurance_provider,service,diagnosis_category,physician_order,clinical_notes,previous_imaging,authorization_status,prompt_type,model
0,P1001,45,Female,HealthConnect,MRI Brain,Neurology,True,True,False,Approved,Standard,gpt-4.1-mini
1,P1002,67,Male,Medicare Plus,CT Abdomen with Contrast,Gastroenterology,True,False,True,Pending,Standard,gpt-4.1-mini
2,P1003,29,Female,WellCare,Physical Therapy Sessions,Orthopedics,True,True,False,Denied,Standard,gpt-4.1-mini
3,P1004,53,Male,SecureHealth,Cardiac Stress Test,Cardiology,False,False,True,Denied,Standard,gpt-4.1-mini
4,P1005,38,Female,PrimeCare,Ultrasound Pelvis,Gynecology,True,True,True,Approved,Standard,gpt-4.1-mini
5,A1001,72,Female,HealthSecure Plus,MRI Brain with Contrast,Neurology,Order for MRI to evaluate new onset seizures,Patient presents with recent episodes of confu...,CT Head without contrast from 3 months ago,Approved,Diversity,gpt-4.1-mini
6,B2345,34,Male,CareFirst National,Physical Therapy - 12 sessions,Orthopedics,PT recommended for post-ACL reconstruction reh...,Recent ACL surgery completed 2 weeks prior; th...,None,Pending,Diversity,gpt-4.1-mini
7,C9876,16,Non-binary,YouthWell Coverage,Psychiatric Evaluation,Mental Health,Assessment requested for anxiety and mood diso...,Adolescent exhibiting signs of social withdraw...,None,Denied,Diversity,gpt-4.1-mini
8,D5412,55,Male,Arbor HealthPlan,Cardiac Stress Test,Cardiology,Stress test ordered due to chest pain and shor...,Patient with hypertension and family history o...,Resting ECG and Echocardiogram reports available,Approved,Diversity,gpt-4.1-mini
9,E3087,3,Female,BrightStart Insurance,Allergy Testing Panel,Pediatrics/Immunology,Panel testing for suspected food allergies due...,Child has developed eczema and food intoleranc...,None,Pending,Diversity,gpt-4.1-mini
10,P10001,58,Female,HealthOne,MRI Brain Scan,Neurology,True,True,False,Pending,Edge Case,gpt-4.1-mini
11,P10002,45,Male,WellCare,Physical Therapy,Orthopedics,False,True,True,Denied,Edge Case,gpt-4.1-mini
12,P10003,32,Female,MediPlus,CT Chest with Contrast,Pulmonology,True,False,True,Denied,Edge Case,gpt-4.1-mini
13,P10004,67,Male,CareFirst,Colonoscopy,Gastroenterology,True,True,True,Approved,Edge Case,gpt-4.1-mini
14,P10005,29,Female,PrimeHealth,Echocardiogram,Cardiology,True,True,False,Pending,Edge Case,gpt-4.1-mini

In [48]:
print("Total records:", len(larger_df))
print("Total columns:", len(larger_df.columns))

print("\nRecords by prompt:")
print(larger_df["prompt_type"].value_counts())

Total records: 15
Total columns: 12

Records by prompt:
prompt_type
Standard     5
Diversity    5
Edge Case    5
Name: count, dtype: int64

## Data Quality Check

Before using synthetic data, we should check whether the generated records contain missing values, duplicates or invalid values.

In [50]:
print("Total records:", len(larger_df))
print("Missing values:", larger_df.isnull().sum().sum())
print("Duplicate records:", larger_df.duplicated().sum())
print("Duplicate patient IDs:", larger_df["patient_id"].duplicated().sum())

invalid_ages = larger_df[
    (larger_df["age"] < 0) | (larger_df["age"] > 120)
]

print("Invalid ages:", len(invalid_ages))

Total records: 15
Missing values: 3
Duplicate records: 0
Duplicate patient IDs: 0
Invalid ages: 0

In [ ]:
# Check Authorization Status
valid_statuses = ["Approved", "Pending", "Denied"]

invalid_statuses = larger_df[~larger_df["authorization_status"].isin(valid_statuses)
]

print(larger_df["authorization_status"].value_counts())

print("\nInvalid statuses:", len(invalid_statuses))

authorization_status
Approved    5
Pending     5
Denied      5
Name: count, dtype: int64

Invalid statuses: 0

## Explore the Synthetic Dataset

Now we will perform a simple analysis to understand the distribution of the generated records.

In [52]:
print("Authorization Status Distribution:")
print(larger_df["authorization_status"].value_counts())

print("\nRecords by Prompt Type:")
print(larger_df["prompt_type"].value_counts())

print("\nUnique Services:")
print(larger_df["service"].nunique())

print("\nUnique Diagnosis Categories:")
print(larger_df["diagnosis_category"].nunique())

Authorization Status Distribution:
authorization_status
Approved    5
Pending     5
Denied      5
Name: count, dtype: int64

Records by Prompt Type:
prompt_type
Standard     5
Diversity    5
Edge Case    5
Name: count, dtype: int64

Unique Services:
14

Unique Diagnosis Categories:
8

This simple analysis helps us understand the variety and distribution of the synthetic data.

Different prompt strategies can be used to generate general, diverse and edge-case records.

## Export the Synthetic Dataset

The final synthetic dataset can be saved and reused in future data science, analytics or AI projects.

In [53]:
larger_df.to_csv(
    "synthetic_prior_authorization_data.csv",
    index=False
)

larger_df.to_json(
    "synthetic_prior_authorization_data.json",
    orient="records",
    indent=4
)

print("Dataset exported successfully.")

Dataset exported successfully.

The synthetic dataset has been exported in both CSV and JSON formats.

CSV can be useful for data analysis and machine learning, while JSON can be useful for APIs and AI applications.

# Conclusion

In this project, we built a Synthetic Healthcare Data Factory for fictional Prior Authorization data.

We:

- Defined the dataset structure and purpose
- Used different prompt strategies
- Generated data using GPT, Llama and Gemini
- Converted LLM responses into structured Pandas DataFrames
- Combined multiple batches of synthetic data
- Added model and prompt metadata
- Performed basic data quality checks
- Analyzed the generated dataset
- Exported the final data as CSV and JSON

This project demonstrates how multiple LLMs and prompt strategies can be used to create reusable synthetic datasets without using real patient information.

The same approach can be extended to other domains and larger datasets.